#define RPC___cudaRegisterVar 0
#define RPC___cudaRegisterFunction 1
#define RPC___cudaRegisterFatBinary 2
#define RPC___cudaRegisterFatBinaryEnd 3
#define RPC___cudaPushCallConfiguration 4
#define RPC___cudaPopCallConfiguration 5
#define RPC_nvmlInit_v2 6
#define RPC_nvmlInitWithFlags 7
#define RPC_nvmlShutdown 8
#define RPC_nvmlErrorString 9
#define RPC_nvmlSystemGetDriverVersion 10
#define RPC_nvmlSystemGetNVMLVersion 11
#define RPC_nvmlSystemGetCudaDriverVersion 12
#define RPC_nvmlSystemGetCudaDriverVersion_v2 13
#define RPC_nvmlSystemGetProcessName 14
#define RPC_nvmlUnitGetCount 15
#define RPC_nvmlUnitGetHandleByIndex 16
#define RPC_nvmlUnitGetUnitInfo 17
#define RPC_nvmlUnitGetLedState 18
#define RPC_nvmlUnitGetPsuInfo 19
#define RPC_nvmlUnitGetTemperature 20
#define RPC_nvmlUnitGetFanSpeedInfo 21
#define RPC_nvmlUnitGetDevices 22
#define RPC_nvmlSystemGetHicVersion 23
#define RPC_nvmlDeviceGetCount_v2 24
#define RPC_nvmlDeviceGetAttributes_v2 25
#define RPC_nvmlDeviceGetHandleByIndex_v2 26
#define RPC_nvmlDeviceGetHandleBySerial 27
#define RPC_nvmlDeviceGetHandleByUUID 28
#define RPC_nvmlDeviceGetHandleByPciBusId_v2 29
#define RPC_nvmlDeviceGetName 30
#define RPC_nvmlDeviceGetBrand 31
#define RPC_nvmlDeviceGetIndex 32
#define RPC_nvmlDeviceGetSerial 33
#define RPC_nvmlDeviceGetMemoryAffinity 34
#define RPC_nvmlDeviceGetCpuAffinityWithinScope 35
#define RPC_nvmlDeviceGetCpuAffinity 36
#define RPC_nvmlDeviceSetCpuAffinity 37
#define RPC_nvmlDeviceClearCpuAffinity 38
#define RPC_nvmlDeviceGetTopologyCommonAncestor 39
#define RPC_nvmlDeviceGetTopologyNearestGpus 40
#define RPC_nvmlSystemGetTopologyGpuSet 41
#define RPC_nvmlDeviceGetP2PStatus 42
#define RPC_nvmlDeviceGetUUID 43
#define RPC_nvmlVgpuInstanceGetMdevUUID 44
#define RPC_nvmlDeviceGetMinorNumber 45
#define RPC_nvmlDeviceGetBoardPartNumber 46
#define RPC_nvmlDeviceGetInforomVersion 47
#define RPC_nvmlDeviceGetInforomImageVersion 48
#define RPC_nvmlDeviceGetInforomConfigurationChecksum 49
#define RPC_nvmlDeviceValidateInforom 50
#define RPC_nvmlDeviceGetDisplayMode 51
#define RPC_nvmlDeviceGetDisplayActive 52
#define RPC_nvmlDeviceGetPersistenceMode 53
#define RPC_nvmlDeviceGetPciInfo_v3 54
#define RPC_nvmlDeviceGetMaxPcieLinkGeneration 55
#define RPC_nvmlDeviceGetMaxPcieLinkWidth 56
#define RPC_nvmlDeviceGetCurrPcieLinkGeneration 57
#define RPC_nvmlDeviceGetCurrPcieLinkWidth 58
#define RPC_nvmlDeviceGetPcieThroughput 59
#define RPC_nvmlDeviceGetPcieReplayCounter 60
#define RPC_nvmlDeviceGetClockInfo 61
#define RPC_nvmlDeviceGetMaxClockInfo 62
#define RPC_nvmlDeviceGetApplicationsClock 63
#define RPC_nvmlDeviceGetDefaultApplicationsClock 64
#define RPC_nvmlDeviceResetApplicationsClocks 65
#define RPC_nvmlDeviceGetClock 66
#define RPC_nvmlDeviceGetMaxCustomerBoostClock 67
#define RPC_nvmlDeviceGetSupportedMemoryClocks 68
#define RPC_nvmlDeviceGetSupportedGraphicsClocks 69
#define RPC_nvmlDeviceGetAutoBoostedClocksEnabled 70
#define RPC_nvmlDeviceSetAutoBoostedClocksEnabled 71
#define RPC_nvmlDeviceSetDefaultAutoBoostedClocksEnabled 72
#define RPC_nvmlDeviceGetFanSpeed 73
#define RPC_nvmlDeviceGetFanSpeed_v2 74
#define RPC_nvmlDeviceGetTemperature 75
#define RPC_nvmlDeviceGetTemperatureThreshold 76
#define RPC_nvmlDeviceSetTemperatureThreshold 77
#define RPC_nvmlDeviceGetPerformanceState 78
#define RPC_nvmlDeviceGetCurrentClocksThrottleReasons 79
#define RPC_nvmlDeviceGetSupportedClocksThrottleReasons 80
#define RPC_nvmlDeviceGetPowerState 81
#define RPC_nvmlDeviceGetPowerManagementMode 82
#define RPC_nvmlDeviceGetPowerManagementLimit 83
#define RPC_nvmlDeviceGetPowerManagementLimitConstraints 84
#define RPC_nvmlDeviceGetPowerManagementDefaultLimit 85
#define RPC_nvmlDeviceGetPowerUsage 86
#define RPC_nvmlDeviceGetTotalEnergyConsumption 87
#define RPC_nvmlDeviceGetEnforcedPowerLimit 88
#define RPC_nvmlDeviceGetGpuOperationMode 89
#define RPC_nvmlDeviceGetMemoryInfo 90
#define RPC_nvmlDeviceGetComputeMode 91
#define RPC_nvmlDeviceGetCudaComputeCapability 92
#define RPC_nvmlDeviceGetEccMode 93
#define RPC_nvmlDeviceGetBoardId 94
#define RPC_nvmlDeviceGetMultiGpuBoard 95
#define RPC_nvmlDeviceGetTotalEccErrors 96
#define RPC_nvmlDeviceGetDetailedEccErrors 97
#define RPC_nvmlDeviceGetMemoryErrorCounter 98
#define RPC_nvmlDeviceGetUtilizationRates 99
#define RPC_nvmlDeviceGetEncoderUtilization 100
#define RPC_nvmlDeviceGetEncoderCapacity 101
#define RPC_nvmlDeviceGetEncoderStats 102
#define RPC_nvmlDeviceGetEncoderSessions 103
#define RPC_nvmlDeviceGetDecoderUtilization 104
#define RPC_nvmlDeviceGetFBCStats 105
#define RPC_nvmlDeviceGetFBCSessions 106
#define RPC_nvmlDeviceGetDriverModel 107
#define RPC_nvmlDeviceGetVbiosVersion 108
#define RPC_nvmlDeviceGetBridgeChipInfo 109
#define RPC_nvmlDeviceOnSameBoard 110
#define RPC_nvmlDeviceGetAPIRestriction 111
#define RPC_nvmlDeviceGetSamples 112
#define RPC_nvmlDeviceGetBAR1MemoryInfo 113
#define RPC_nvmlDeviceGetViolationStatus 114
#define RPC_nvmlDeviceGetIrqNum 115
#define RPC_nvmlDeviceGetAccountingMode 116
#define RPC_nvmlDeviceGetAccountingStats 117
#define RPC_nvmlDeviceGetAccountingPids 118
#define RPC_nvmlDeviceGetAccountingBufferSize 119
#define RPC_nvmlDeviceGetRetiredPages 120
#define RPC_nvmlDeviceGetRetiredPages_v2 121
#define RPC_nvmlDeviceGetRetiredPagesPendingStatus 122
#define RPC_nvmlDeviceGetRemappedRows 123
#define RPC_nvmlDeviceGetRowRemapperHistogram 124
#define RPC_nvmlDeviceGetArchitecture 125
#define RPC_nvmlUnitSetLedState 126
#define RPC_nvmlDeviceSetPersistenceMode 127
#define RPC_nvmlDeviceSetComputeMode 128
#define RPC_nvmlDeviceSetEccMode 129
#define RPC_nvmlDeviceClearEccErrorCounts 130
#define RPC_nvmlDeviceSetDriverModel 131
#define RPC_nvmlDeviceSetGpuLockedClocks 132
#define RPC_nvmlDeviceResetGpuLockedClocks 133
#define RPC_nvmlDeviceSetMemoryLockedClocks 134
#define RPC_nvmlDeviceResetMemoryLockedClocks 135
#define RPC_nvmlDeviceSetApplicationsClocks 136
#define RPC_nvmlDeviceGetClkMonStatus 137
#define RPC_nvmlDeviceSetPowerManagementLimit 138
#define RPC_nvmlDeviceSetGpuOperationMode 139
#define RPC_nvmlDeviceSetAPIRestriction 140
#define RPC_nvmlDeviceSetAccountingMode 141
#define RPC_nvmlDeviceClearAccountingPids 142
#define RPC_nvmlDeviceGetNvLinkState 143
#define RPC_nvmlDeviceGetNvLinkVersion 144
#define RPC_nvmlDeviceGetNvLinkCapability 145
#define RPC_nvmlDeviceGetNvLinkRemotePciInfo_v2 146
#define RPC_nvmlDeviceGetNvLinkErrorCounter 147
#define RPC_nvmlDeviceResetNvLinkErrorCounters 148
#define RPC_nvmlDeviceSetNvLinkUtilizationControl 149
#define RPC_nvmlDeviceGetNvLinkUtilizationControl 150
#define RPC_nvmlDeviceGetNvLinkUtilizationCounter 151
#define RPC_nvmlDeviceFreezeNvLinkUtilizationCounter 152
#define RPC_nvmlDeviceResetNvLinkUtilizationCounter 153
#define RPC_nvmlDeviceGetNvLinkRemoteDeviceType 154
#define RPC_nvmlEventSetCreate 155
#define RPC_nvmlDeviceRegisterEvents 156
#define RPC_nvmlDeviceGetSupportedEventTypes 157
#define RPC_nvmlEventSetWait_v2 158
#define RPC_nvmlEventSetFree 159
#define RPC_nvmlDeviceModifyDrainState 160
#define RPC_nvmlDeviceQueryDrainState 161
#define RPC_nvmlDeviceRemoveGpu_v2 162
#define RPC_nvmlDeviceDiscoverGpus 163
#define RPC_nvmlDeviceGetFieldValues 164
#define RPC_nvmlDeviceGetVirtualizationMode 165
#define RPC_nvmlDeviceGetHostVgpuMode 166
#define RPC_nvmlDeviceSetVirtualizationMode 167
#define RPC_nvmlDeviceGetGridLicensableFeatures_v4 168
#define RPC_nvmlDeviceGetProcessUtilization 169
#define RPC_nvmlDeviceGetSupportedVgpus 170
#define RPC_nvmlDeviceGetCreatableVgpus 171
#define RPC_nvmlVgpuTypeGetClass 172
#define RPC_nvmlVgpuTypeGetName 173
#define RPC_nvmlVgpuTypeGetGpuInstanceProfileId 174
#define RPC_nvmlVgpuTypeGetDeviceID 175
#define RPC_nvmlVgpuTypeGetFramebufferSize 176
#define RPC_nvmlVgpuTypeGetNumDisplayHeads 177
#define RPC_nvmlVgpuTypeGetResolution 178
#define RPC_nvmlVgpuTypeGetLicense 179
#define RPC_nvmlVgpuTypeGetFrameRateLimit 180
#define RPC_nvmlVgpuTypeGetMaxInstances 181
#define RPC_nvmlVgpuTypeGetMaxInstancesPerVm 182
#define RPC_nvmlDeviceGetActiveVgpus 183
#define RPC_nvmlVgpuInstanceGetVmID 184
#define RPC_nvmlVgpuInstanceGetUUID 185
#define RPC_nvmlVgpuInstanceGetVmDriverVersion 186
#define RPC_nvmlVgpuInstanceGetFbUsage 187
#define RPC_nvmlVgpuInstanceGetLicenseStatus 188
#define RPC_nvmlVgpuInstanceGetType 189
#define RPC_nvmlVgpuInstanceGetFrameRateLimit 190
#define RPC_nvmlVgpuInstanceGetEccMode 191
#define RPC_nvmlVgpuInstanceGetEncoderCapacity 192
#define RPC_nvmlVgpuInstanceSetEncoderCapacity 193
#define RPC_nvmlVgpuInstanceGetEncoderStats 194
#define RPC_nvmlVgpuInstanceGetEncoderSessions 195
#define RPC_nvmlVgpuInstanceGetFBCStats 196
#define RPC_nvmlVgpuInstanceGetFBCSessions 197
#define RPC_nvmlVgpuInstanceGetGpuInstanceId 198
#define RPC_nvmlVgpuInstanceGetMetadata 199
#define RPC_nvmlDeviceGetVgpuMetadata 200
#define RPC_nvmlGetVgpuCompatibility 201
#define RPC_nvmlDeviceGetPgpuMetadataString 202
#define RPC_nvmlGetVgpuVersion 203
#define RPC_nvmlSetVgpuVersion 204
#define RPC_nvmlDeviceGetVgpuUtilization 205
#define RPC_nvmlDeviceGetVgpuProcessUtilization 206
#define RPC_nvmlVgpuInstanceGetAccountingMode 207
#define RPC_nvmlVgpuInstanceGetAccountingPids 208
#define RPC_nvmlVgpuInstanceGetAccountingStats 209
#define RPC_nvmlVgpuInstanceClearAccountingPids 210
#define RPC_nvmlGetExcludedDeviceCount 211
#define RPC_nvmlGetExcludedDeviceInfoByIndex 212
#define RPC_nvmlDeviceSetMigMode 213
#define RPC_nvmlDeviceGetMigMode 214
#define RPC_nvmlDeviceGetGpuInstanceProfileInfo 215
#define RPC_nvmlDeviceGetGpuInstancePossiblePlacements_v2 216
#define RPC_nvmlDeviceGetGpuInstanceRemainingCapacity 217
#define RPC_nvmlDeviceCreateGpuInstance 218
#define RPC_nvmlDeviceCreateGpuInstanceWithPlacement 219
#define RPC_nvmlGpuInstanceDestroy 220
#define RPC_nvmlDeviceGetGpuInstances 221
#define RPC_nvmlDeviceGetGpuInstanceById 222
#define RPC_nvmlGpuInstanceGetInfo 223
#define RPC_nvmlGpuInstanceGetComputeInstanceProfileInfo 224
#define RPC_nvmlGpuInstanceGetComputeInstanceRemainingCapacity 225
#define RPC_nvmlGpuInstanceCreateComputeInstance 226
#define RPC_nvmlComputeInstanceDestroy 227
#define RPC_nvmlGpuInstanceGetComputeInstances 228
#define RPC_nvmlGpuInstanceGetComputeInstanceById 229
#define RPC_nvmlComputeInstanceGetInfo_v2 230
#define RPC_nvmlDeviceIsMigDeviceHandle 231
#define RPC_nvmlDeviceGetGpuInstanceId 232
#define RPC_nvmlDeviceGetComputeInstanceId 233
#define RPC_nvmlDeviceGetMaxMigDeviceCount 234
#define RPC_nvmlDeviceGetMigDeviceHandleByIndex 235
#define RPC_nvmlDeviceGetDeviceHandleFromMigDeviceHandle 236
#define RPC_nvmlDeviceGetBusType 237
#define RPC_cuGetErrorString 238
#define RPC_cuGetErrorName 239
#define RPC_cuInit 240
#define RPC_cuDriverGetVersion 241
#define RPC_cuDeviceGet 242
#define RPC_cuDeviceGetCount 243
#define RPC_cuDeviceGetName 244
#define RPC_cuDeviceGetUuid 245
#define RPC_cuDeviceGetUuid_v2 246
#define RPC_cuDeviceGetLuid 247
#define RPC_cuDeviceTotalMem_v2 248
#define RPC_cuDeviceGetTexture1DLinearMaxWidth 249
#define RPC_cuDeviceGetAttribute 250
#define RPC_cuDeviceGetNvSciSyncAttributes 251
#define RPC_cuDeviceSetMemPool 252
#define RPC_cuDeviceGetMemPool 253
#define RPC_cuDeviceGetDefaultMemPool 254
#define RPC_cuDeviceGetExecAffinitySupport 255
#define RPC_cuFlushGPUDirectRDMAWrites 256
#define RPC_cuDeviceGetProperties 257
#define RPC_cuDeviceComputeCapability 258
#define RPC_cuDevicePrimaryCtxRetain 259
#define RPC_cuDevicePrimaryCtxRelease_v2 260
#define RPC_cuDevicePrimaryCtxSetFlags_v2 261
#define RPC_cuDevicePrimaryCtxGetState 262
#define RPC_cuDevicePrimaryCtxReset_v2 263
#define RPC_cuCtxCreate_v2 264
#define RPC_cuCtxCreate_v3 265
#define RPC_cuCtxDestroy_v2 266
#define RPC_cuCtxPushCurrent_v2 267
#define RPC_cuCtxPopCurrent_v2 268
#define RPC_cuCtxSetCurrent 269
#define RPC_cuCtxGetCurrent 270
#define RPC_cuCtxGetDevice 271
#define RPC_cuCtxGetFlags 272
#define RPC_cuCtxGetId 273
#define RPC_cuCtxSynchronize 274
#define RPC_cuCtxSetLimit 275
#define RPC_cuCtxGetLimit 276
#define RPC_cuCtxGetCacheConfig 277
#define RPC_cuCtxSetCacheConfig 278
#define RPC_cuCtxGetApiVersion 279
#define RPC_cuCtxGetStreamPriorityRange 280
#define RPC_cuCtxResetPersistingL2Cache 281
#define RPC_cuCtxGetExecAffinity 282
#define RPC_cuCtxAttach 283
#define RPC_cuCtxDetach 284
#define RPC_cuCtxGetSharedMemConfig 285
#define RPC_cuCtxSetSharedMemConfig 286
#define RPC_cuModuleLoad 287
#define RPC_cuModuleLoadData 288
#define RPC_cuModuleLoadDataEx 289
#define RPC_cuModuleLoadFatBinary 290
#define RPC_cuModuleUnload 291
#define RPC_cuModuleGetLoadingMode 292
#define RPC_cuModuleGetFunction 293
#define RPC_cuModuleGetGlobal_v2 294
#define RPC_cuLinkCreate_v2 295
#define RPC_cuLinkAddFile_v2 296
#define RPC_cuLinkComplete 297
#define RPC_cuLinkDestroy 298
#define RPC_cuModuleGetTexRef 299
#define RPC_cuModuleGetSurfRef 300
#define RPC_cuLibraryLoadData 301
#define RPC_cuLibraryLoadFromFile 302
#define RPC_cuLibraryUnload 303
#define RPC_cuLibraryGetKernel 304
#define RPC_cuLibraryGetModule 305
#define RPC_cuKernelGetFunction 306
#define RPC_cuLibraryGetGlobal 307
#define RPC_cuLibraryGetManaged 308
#define RPC_cuLibraryGetUnifiedFunction 309
#define RPC_cuKernelGetAttribute 310
#define RPC_cuKernelSetAttribute 311
#define RPC_cuKernelSetCacheConfig 312
#define RPC_cuMemGetInfo_v2 313
#define RPC_cuMemAlloc_v2 314
#define RPC_cuMemAllocPitch_v2 315
#define RPC_cuMemFree_v2 316
#define RPC_cuMemGetAddressRange_v2 317
#define RPC_cuMemAllocHost_v2 318
#define RPC_cuMemFreeHost 319
#define RPC_cuMemHostAlloc 320
#define RPC_cuMemHostGetDevicePointer_v2 321
#define RPC_cuMemHostGetFlags 322
#define RPC_cuMemAllocManaged 323
#define RPC_cuDeviceGetByPCIBusId 324
#define RPC_cuDeviceGetPCIBusId 325
#define RPC_cuIpcGetEventHandle 326
#define RPC_cuIpcOpenEventHandle 327
#define RPC_cuIpcGetMemHandle 328
#define RPC_cuIpcOpenMemHandle_v2 329
#define RPC_cuIpcCloseMemHandle 330
#define RPC_cuMemcpy 331
#define RPC_cuMemcpyPeer 332
#define RPC_cuMemcpyHtoD_v2 333
#define RPC_cuMemcpyDtoD_v2 334
#define RPC_cuMemcpyDtoA_v2 335
#define RPC_cuMemcpyAtoD_v2 336
#define RPC_cuMemcpyHtoA_v2 337
#define RPC_cuMemcpyAtoH_v2 338
#define RPC_cuMemcpyAtoA_v2 339
#define RPC_cuMemcpy2D_v2 340
#define RPC_cuMemcpy2DUnaligned_v2 341
#define RPC_cuMemcpy3D_v2 342
#define RPC_cuMemcpy3DPeer 343
#define RPC_cuMemcpyAsync 344
#define RPC_cuMemcpyPeerAsync 345
#define RPC_cuMemcpyHtoDAsync_v2 346
#define RPC_cuMemcpyDtoDAsync_v2 347
#define RPC_cuMemcpyHtoAAsync_v2 348
#define RPC_cuMemcpy2DAsync_v2 349
#define RPC_cuMemcpy3DAsync_v2 350
#define RPC_cuMemcpy3DPeerAsync 351
#define RPC_cuMemsetD8_v2 352
#define RPC_cuMemsetD16_v2 353
#define RPC_cuMemsetD32_v2 354
#define RPC_cuMemsetD2D8_v2 355
#define RPC_cuMemsetD2D16_v2 356
#define RPC_cuMemsetD2D32_v2 357
#define RPC_cuMemsetD8Async 358
#define RPC_cuMemsetD16Async 359
#define RPC_cuMemsetD32Async 360
#define RPC_cuMemsetD2D8Async 361
#define RPC_cuMemsetD2D16Async 362
#define RPC_cuMemsetD2D32Async 363
#define RPC_cuArrayCreate_v2 364
#define RPC_cuArrayGetDescriptor_v2 365
#define RPC_cuArrayGetSparseProperties 366
#define RPC_cuMipmappedArrayGetSparseProperties 367
#define RPC_cuArrayGetMemoryRequirements 368
#define RPC_cuMipmappedArrayGetMemoryRequirements 369
#define RPC_cuArrayGetPlane 370
#define RPC_cuArrayDestroy 371
#define RPC_cuArray3DCreate_v2 372
#define RPC_cuArray3DGetDescriptor_v2 373
#define RPC_cuMipmappedArrayCreate 374
#define RPC_cuMipmappedArrayGetLevel 375
#define RPC_cuMipmappedArrayDestroy 376
#define RPC_cuMemAddressReserve 377
#define RPC_cuMemAddressFree 378
#define RPC_cuMemCreate 379
#define RPC_cuMemRelease 380
#define RPC_cuMemMap 381
#define RPC_cuMemMapArrayAsync 382
#define RPC_cuMemUnmap 383
#define RPC_cuMemSetAccess 384
#define RPC_cuMemGetAccess 385
#define RPC_cuMemGetAllocationGranularity 386
#define RPC_cuMemGetAllocationPropertiesFromHandle 387
#define RPC_cuMemFreeAsync 388
#define RPC_cuMemAllocAsync 389
#define RPC_cuMemPoolTrimTo 390
#define RPC_cuMemPoolSetAccess 391
#define RPC_cuMemPoolGetAccess 392
#define RPC_cuMemPoolCreate 393
#define RPC_cuMemPoolDestroy 394
#define RPC_cuMemAllocFromPoolAsync 395
#define RPC_cuMemPoolExportPointer 396
#define RPC_cuMemPoolImportPointer 397
#define RPC_cuMemPrefetchAsync 398
#define RPC_cuMemAdvise 399
#define RPC_cuMemRangeGetAttributes 400
#define RPC_cuPointerSetAttribute 401
#define RPC_cuPointerGetAttributes 402
#define RPC_cuStreamCreate 403
#define RPC_cuStreamCreateWithPriority 404
#define RPC_cuStreamGetPriority 405
#define RPC_cuStreamGetFlags 406
#define RPC_cuStreamGetId 407
#define RPC_cuStreamGetCtx 408
#define RPC_cuStreamWaitEvent 409
#define RPC_cuStreamBeginCapture_v2 410
#define RPC_cuThreadExchangeStreamCaptureMode 411
#define RPC_cuStreamEndCapture 412
#define RPC_cuStreamIsCapturing 413
#define RPC_cuStreamGetCaptureInfo_v2 414
#define RPC_cuStreamUpdateCaptureDependencies 415
#define RPC_cuStreamAttachMemAsync 416
#define RPC_cuStreamQuery 417
#define RPC_cuStreamSynchronize 418
#define RPC_cuStreamDestroy_v2 419
#define RPC_cuStreamCopyAttributes 420
#define RPC_cuStreamGetAttribute 421
#define RPC_cuStreamSetAttribute 422
#define RPC_cuEventCreate 423
#define RPC_cuEventRecord 424
#define RPC_cuEventRecordWithFlags 425
#define RPC_cuEventQuery 426
#define RPC_cuEventSynchronize 427
#define RPC_cuEventDestroy_v2 428
#define RPC_cuEventElapsedTime 429
#define RPC_cuImportExternalMemory 430
#define RPC_cuExternalMemoryGetMappedBuffer 431
#define RPC_cuExternalMemoryGetMappedMipmappedArray 432
#define RPC_cuDestroyExternalMemory 433
#define RPC_cuImportExternalSemaphore 434
#define RPC_cuSignalExternalSemaphoresAsync 435
#define RPC_cuWaitExternalSemaphoresAsync 436
#define RPC_cuDestroyExternalSemaphore 437
#define RPC_cuStreamWaitValue32_v2 438
#define RPC_cuStreamWaitValue64_v2 439
#define RPC_cuStreamWriteValue32_v2 440
#define RPC_cuStreamWriteValue64_v2 441
#define RPC_cuStreamBatchMemOp_v2 442
#define RPC_cuFuncGetAttribute 443
#define RPC_cuFuncSetAttribute 444
#define RPC_cuFuncSetCacheConfig 445
#define RPC_cuFuncGetModule 446
#define RPC_cuLaunchKernel 447
#define RPC_cuLaunchKernelEx 448
#define RPC_cuLaunchCooperativeKernel 449
#define RPC_cuLaunchCooperativeKernelMultiDevice 450
#define RPC_cuFuncSetBlockShape 451
#define RPC_cuFuncSetSharedSize 452
#define RPC_cuParamSetSize 453
#define RPC_cuParamSeti 454
#define RPC_cuParamSetf 455
#define RPC_cuLaunch 456
#define RPC_cuLaunchGrid 457
#define RPC_cuLaunchGridAsync 458
#define RPC_cuParamSetTexRef 459
#define RPC_cuFuncSetSharedMemConfig 460
#define RPC_cuGraphCreate 461
#define RPC_cuGraphAddKernelNode_v2 462
#define RPC_cuGraphKernelNodeGetParams_v2 463
#define RPC_cuGraphKernelNodeSetParams_v2 464
#define RPC_cuGraphAddMemcpyNode 465
#define RPC_cuGraphMemcpyNodeGetParams 466
#define RPC_cuGraphMemcpyNodeSetParams 467
#define RPC_cuGraphAddMemsetNode 468
#define RPC_cuGraphMemsetNodeGetParams 469
#define RPC_cuGraphMemsetNodeSetParams 470
#define RPC_cuGraphAddHostNode 471
#define RPC_cuGraphHostNodeGetParams 472
#define RPC_cuGraphHostNodeSetParams 473
#define RPC_cuGraphAddChildGraphNode 474
#define RPC_cuGraphChildGraphNodeGetGraph 475
#define RPC_cuGraphAddEmptyNode 476
#define RPC_cuGraphAddEventRecordNode 477
#define RPC_cuGraphEventRecordNodeGetEvent 478
#define RPC_cuGraphEventRecordNodeSetEvent 479
#define RPC_cuGraphAddEventWaitNode 480
#define RPC_cuGraphEventWaitNodeGetEvent 481
#define RPC_cuGraphEventWaitNodeSetEvent 482
#define RPC_cuGraphAddExternalSemaphoresSignalNode 483
#define RPC_cuGraphExternalSemaphoresSignalNodeGetParams 484
#define RPC_cuGraphExternalSemaphoresSignalNodeSetParams 485
#define RPC_cuGraphAddExternalSemaphoresWaitNode 486
#define RPC_cuGraphExternalSemaphoresWaitNodeGetParams 487
#define RPC_cuGraphExternalSemaphoresWaitNodeSetParams 488
#define RPC_cuGraphAddBatchMemOpNode 489
#define RPC_cuGraphBatchMemOpNodeGetParams 490
#define RPC_cuGraphBatchMemOpNodeSetParams 491
#define RPC_cuGraphExecBatchMemOpNodeSetParams 492
#define RPC_cuGraphAddMemAllocNode 493
#define RPC_cuGraphMemAllocNodeGetParams 494
#define RPC_cuGraphAddMemFreeNode 495
#define RPC_cuGraphMemFreeNodeGetParams 496
#define RPC_cuDeviceGraphMemTrim 497
#define RPC_cuGraphClone 498
#define RPC_cuGraphNodeFindInClone 499
#define RPC_cuGraphNodeGetType 500
#define RPC_cuGraphGetNodes 501
#define RPC_cuGraphGetRootNodes 502
#define RPC_cuGraphGetEdges 503
#define RPC_cuGraphNodeGetDependencies 504
#define RPC_cuGraphNodeGetDependentNodes 505
#define RPC_cuGraphAddDependencies 506
#define RPC_cuGraphRemoveDependencies 507
#define RPC_cuGraphDestroyNode 508
#define RPC_cuGraphInstantiateWithFlags 509
#define RPC_cuGraphInstantiateWithParams 510
#define RPC_cuGraphExecGetFlags 511
#define RPC_cuGraphExecKernelNodeSetParams_v2 512
#define RPC_cuGraphExecMemcpyNodeSetParams 513
#define RPC_cuGraphExecMemsetNodeSetParams 514
#define RPC_cuGraphExecHostNodeSetParams 515
#define RPC_cuGraphExecChildGraphNodeSetParams 516
#define RPC_cuGraphExecEventRecordNodeSetEvent 517
#define RPC_cuGraphExecEventWaitNodeSetEvent 518
#define RPC_cuGraphExecExternalSemaphoresSignalNodeSetParams 519
#define RPC_cuGraphExecExternalSemaphoresWaitNodeSetParams 520
#define RPC_cuGraphNodeSetEnabled 521
#define RPC_cuGraphNodeGetEnabled 522
#define RPC_cuGraphUpload 523
#define RPC_cuGraphLaunch 524
#define RPC_cuGraphExecDestroy 525
#define RPC_cuGraphDestroy 526
#define RPC_cuGraphExecUpdate_v2 527
#define RPC_cuGraphKernelNodeCopyAttributes 528
#define RPC_cuGraphKernelNodeGetAttribute 529
#define RPC_cuGraphKernelNodeSetAttribute 530
#define RPC_cuGraphDebugDotPrint 531
#define RPC_cuUserObjectRetain 532
#define RPC_cuUserObjectRelease 533
#define RPC_cuGraphRetainUserObject 534
#define RPC_cuGraphReleaseUserObject 535
#define RPC_cuOccupancyMaxActiveBlocksPerMultiprocessor 536
#define RPC_cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags 537
#define RPC_cuOccupancyMaxPotentialBlockSize 538
#define RPC_cuOccupancyMaxPotentialBlockSizeWithFlags 539
#define RPC_cuOccupancyAvailableDynamicSMemPerBlock 540
#define RPC_cuOccupancyMaxPotentialClusterSize 541
#define RPC_cuOccupancyMaxActiveClusters 542
#define RPC_cuTexRefSetArray 543
#define RPC_cuTexRefSetMipmappedArray 544
#define RPC_cuTexRefSetAddress_v2 545
#define RPC_cuTexRefSetAddress2D_v3 546
#define RPC_cuTexRefSetFormat 547
#define RPC_cuTexRefSetAddressMode 548
#define RPC_cuTexRefSetFilterMode 549
#define RPC_cuTexRefSetMipmapFilterMode 550
#define RPC_cuTexRefSetMipmapLevelBias 551
#define RPC_cuTexRefSetMipmapLevelClamp 552
#define RPC_cuTexRefSetMaxAnisotropy 553
#define RPC_cuTexRefSetBorderColor 554
#define RPC_cuTexRefSetFlags 555
#define RPC_cuTexRefGetAddress_v2 556
#define RPC_cuTexRefGetArray 557
#define RPC_cuTexRefGetMipmappedArray 558
#define RPC_cuTexRefGetAddressMode 559
#define RPC_cuTexRefGetFilterMode 560
#define RPC_cuTexRefGetFormat 561
#define RPC_cuTexRefGetMipmapFilterMode 562
#define RPC_cuTexRefGetMipmapLevelBias 563
#define RPC_cuTexRefGetMipmapLevelClamp 564
#define RPC_cuTexRefGetMaxAnisotropy 565
#define RPC_cuTexRefGetBorderColor 566
#define RPC_cuTexRefGetFlags 567
#define RPC_cuTexRefCreate 568
#define RPC_cuTexRefDestroy 569
#define RPC_cuSurfRefSetArray 570
#define RPC_cuSurfRefGetArray 571
#define RPC_cuTexObjectCreate 572
#define RPC_cuTexObjectDestroy 573
#define RPC_cuTexObjectGetResourceDesc 574
#define RPC_cuTexObjectGetTextureDesc 575
#define RPC_cuTexObjectGetResourceViewDesc 576
#define RPC_cuSurfObjectCreate 577
#define RPC_cuSurfObjectDestroy 578
#define RPC_cuSurfObjectGetResourceDesc 579
#define RPC_cuDeviceCanAccessPeer 580
#define RPC_cuCtxEnablePeerAccess 581
#define RPC_cuCtxDisablePeerAccess 582
#define RPC_cuDeviceGetP2PAttribute 583
#define RPC_cuGraphicsUnregisterResource 584
#define RPC_cuGraphicsSubResourceGetMappedArray 585
#define RPC_cuGraphicsResourceGetMappedMipmappedArray 586
#define RPC_cuGraphicsResourceGetMappedPointer_v2 587
#define RPC_cuGraphicsResourceSetMapFlags_v2 588
#define RPC_cuGraphicsMapResources 589
#define RPC_cuGraphicsUnmapResources 590
#define RPC_cuGetProcAddress_v2 591
#define RPC_cuGetExportTable 592
#define RPC_cudaDeviceReset 593
#define RPC_cudaDeviceSynchronize 594
#define RPC_cudaDeviceSetLimit 595
#define RPC_cudaDeviceGetLimit 596
#define RPC_cudaDeviceGetTexture1DLinearMaxWidth 597
#define RPC_cudaDeviceGetCacheConfig 598
#define RPC_cudaDeviceGetStreamPriorityRange 599
#define RPC_cudaDeviceSetCacheConfig 600
#define RPC_cudaDeviceGetByPCIBusId 601
#define RPC_cudaDeviceGetPCIBusId 602
#define RPC_cudaIpcGetEventHandle 603
#define RPC_cudaIpcOpenEventHandle 604
#define RPC_cudaIpcOpenMemHandle 605
#define RPC_cudaDeviceFlushGPUDirectRDMAWrites 606
#define RPC_cudaDeviceGetSharedMemConfig 607
#define RPC_cudaDeviceSetSharedMemConfig 608
#define RPC_cudaThreadExit 609
#define RPC_cudaThreadSynchronize 610
#define RPC_cudaThreadSetLimit 611
#define RPC_cudaThreadGetLimit 612
#define RPC_cudaThreadGetCacheConfig 613
#define RPC_cudaThreadSetCacheConfig 614
#define RPC_cudaGetLastError 615
#define RPC_cudaPeekAtLastError 616
#define RPC_cudaGetErrorName 617
#define RPC_cudaGetErrorString 618
#define RPC_cudaGetDeviceCount 619
#define RPC_cudaGetDeviceProperties_v2 620
#define RPC_cudaDeviceGetAttribute 621
#define RPC_cudaDeviceGetDefaultMemPool 622
#define RPC_cudaDeviceSetMemPool 623
#define RPC_cudaDeviceGetMemPool 624
#define RPC_cudaDeviceGetP2PAttribute 625
#define RPC_cudaChooseDevice 626
#define RPC_cudaInitDevice 627
#define RPC_cudaSetDevice 628
#define RPC_cudaGetDevice 629
#define RPC_cudaSetValidDevices 630
#define RPC_cudaSetDeviceFlags 631
#define RPC_cudaGetDeviceFlags 632
#define RPC_cudaStreamCreate 633
#define RPC_cudaStreamCreateWithFlags 634
#define RPC_cudaStreamCreateWithPriority 635
#define RPC_cudaStreamGetPriority 636
#define RPC_cudaStreamGetFlags 637
#define RPC_cudaStreamGetId 638
#define RPC_cudaCtxResetPersistingL2Cache 639
#define RPC_cudaStreamCopyAttributes 640
#define RPC_cudaStreamGetAttribute 641
#define RPC_cudaStreamSetAttribute 642
#define RPC_cudaStreamDestroy 643
#define RPC_cudaStreamWaitEvent 644
#define RPC_cudaStreamSynchronize 645
#define RPC_cudaStreamQuery 646
#define RPC_cudaStreamBeginCapture 647
#define RPC_cudaThreadExchangeStreamCaptureMode 648
#define RPC_cudaStreamEndCapture 649
#define RPC_cudaStreamIsCapturing 650
#define RPC_cudaStreamGetCaptureInfo_v2 651
#define RPC_cudaStreamUpdateCaptureDependencies 652
#define RPC_cudaEventCreate 653
#define RPC_cudaEventCreateWithFlags 654
#define RPC_cudaEventRecord 655
#define RPC_cudaEventRecordWithFlags 656
#define RPC_cudaEventQuery 657
#define RPC_cudaEventSynchronize 658
#define RPC_cudaEventDestroy 659
#define RPC_cudaEventElapsedTime 660
#define RPC_cudaImportExternalMemory 661
#define RPC_cudaExternalMemoryGetMappedBuffer 662
#define RPC_cudaExternalMemoryGetMappedMipmappedArray 663
#define RPC_cudaDestroyExternalMemory 664
#define RPC_cudaImportExternalSemaphore 665
#define RPC_cudaSignalExternalSemaphoresAsync_v2 666
#define RPC_cudaWaitExternalSemaphoresAsync_v2 667
#define RPC_cudaDestroyExternalSemaphore 668
#define RPC_cudaLaunchKernel 669
#define RPC_cudaLaunchKernelExC 670
#define RPC_cudaLaunchCooperativeKernel 671
#define RPC_cudaLaunchCooperativeKernelMultiDevice 672
#define RPC_cudaFuncSetCacheConfig 673
#define RPC_cudaFuncGetAttributes 674
#define RPC_cudaFuncSetAttribute 675
#define RPC_cudaSetDoubleForDevice 676
#define RPC_cudaSetDoubleForHost 677
#define RPC_cudaFuncSetSharedMemConfig 678
#define RPC_cudaOccupancyMaxActiveBlocksPerMultiprocessor 679
#define RPC_cudaOccupancyAvailableDynamicSMemPerBlock 680
#define RPC_cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags 681
#define RPC_cudaOccupancyMaxPotentialClusterSize 682
#define RPC_cudaOccupancyMaxActiveClusters 683
#define RPC_cudaMallocManaged 684
#define RPC_cudaMalloc 685
#define RPC_cudaMallocHost 686
#define RPC_cudaMallocPitch 687
#define RPC_cudaMallocArray 688
#define RPC_cudaFree 689
#define RPC_cudaFreeHost 690
#define RPC_cudaFreeArray 691
#define RPC_cudaFreeMipmappedArray 692
#define RPC_cudaHostAlloc 693
#define RPC_cudaMalloc3D 694
#define RPC_cudaMalloc3DArray 695
#define RPC_cudaMallocMipmappedArray 696
#define RPC_cudaGetMipmappedArrayLevel 697
#define RPC_cudaMemcpy3D 698
#define RPC_cudaMemcpy3DPeer 699
#define RPC_cudaMemcpy3DAsync 700
#define RPC_cudaMemcpy3DPeerAsync 701
#define RPC_cudaMemGetInfo 702
#define RPC_cudaArrayGetInfo 703
#define RPC_cudaArrayGetPlane 704
#define RPC_cudaArrayGetMemoryRequirements 705
#define RPC_cudaMipmappedArrayGetMemoryRequirements 706
#define RPC_cudaArrayGetSparseProperties 707
#define RPC_cudaMipmappedArrayGetSparseProperties 708
#define RPC_cudaMemcpy 709
#define RPC_cudaMemcpy2DToArray 710
#define RPC_cudaMemcpy2DArrayToArray 711
#define RPC_cudaMemcpyToSymbol 712
#define RPC_cudaMemcpyAsync 713
#define RPC_cudaMemcpy2DToArrayAsync 714
#define RPC_cudaMemcpyToSymbolAsync 715
#define RPC_cudaMemset 716
#define RPC_cudaMemset2D 717
#define RPC_cudaMemset3D 718
#define RPC_cudaMemsetAsync 719
#define RPC_cudaMemset2DAsync 720
#define RPC_cudaMemset3DAsync 721
#define RPC_cudaGetSymbolAddress 722
#define RPC_cudaGetSymbolSize 723
#define RPC_cudaMemPrefetchAsync 724
#define RPC_cudaMemAdvise 725
#define RPC_cudaMemRangeGetAttributes 726
#define RPC_cudaMemcpyToArray 727
#define RPC_cudaMemcpyArrayToArray 728
#define RPC_cudaMemcpyToArrayAsync 729
#define RPC_cudaMallocAsync 730
#define RPC_cudaMemPoolTrimTo 731
#define RPC_cudaMemPoolSetAccess 732
#define RPC_cudaMemPoolGetAccess 733
#define RPC_cudaMemPoolCreate 734
#define RPC_cudaMemPoolDestroy 735
#define RPC_cudaMallocFromPoolAsync 736
#define RPC_cudaMemPoolImportPointer 737
#define RPC_cudaPointerGetAttributes 738
#define RPC_cudaDeviceCanAccessPeer 739
#define RPC_cudaDeviceEnablePeerAccess 740
#define RPC_cudaDeviceDisablePeerAccess 741
#define RPC_cudaGraphicsUnregisterResource 742
#define RPC_cudaGraphicsResourceSetMapFlags 743
#define RPC_cudaGraphicsMapResources 744
#define RPC_cudaGraphicsUnmapResources 745
#define RPC_cudaGraphicsResourceGetMappedPointer 746
#define RPC_cudaGraphicsSubResourceGetMappedArray 747
#define RPC_cudaGraphicsResourceGetMappedMipmappedArray 748
#define RPC_cudaGetChannelDesc 749
#define RPC_cudaCreateChannelDesc 750
#define RPC_cudaCreateTextureObject 751
#define RPC_cudaDestroyTextureObject 752
#define RPC_cudaGetTextureObjectResourceDesc 753
#define RPC_cudaGetTextureObjectTextureDesc 754
#define RPC_cudaGetTextureObjectResourceViewDesc 755
#define RPC_cudaCreateSurfaceObject 756
#define RPC_cudaDestroySurfaceObject 757
#define RPC_cudaGetSurfaceObjectResourceDesc 758
#define RPC_cudaDriverGetVersion 759
#define RPC_cudaRuntimeGetVersion 760
#define RPC_cudaGraphCreate 761
#define RPC_cudaGraphAddKernelNode 762
#define RPC_cudaGraphKernelNodeGetParams 763
#define RPC_cudaGraphKernelNodeSetParams 764
#define RPC_cudaGraphKernelNodeCopyAttributes 765
#define RPC_cudaGraphKernelNodeGetAttribute 766
#define RPC_cudaGraphKernelNodeSetAttribute 767
#define RPC_cudaGraphAddMemcpyNode 768
#define RPC_cudaGraphAddMemcpyNodeToSymbol 769
#define RPC_cudaGraphMemcpyNodeGetParams 770
#define RPC_cudaGraphMemcpyNodeSetParams 771
#define RPC_cudaGraphMemcpyNodeSetParamsToSymbol 772
#define RPC_cudaGraphAddMemsetNode 773
#define RPC_cudaGraphMemsetNodeGetParams 774
#define RPC_cudaGraphMemsetNodeSetParams 775
#define RPC_cudaGraphAddHostNode 776
#define RPC_cudaGraphHostNodeGetParams 777
#define RPC_cudaGraphHostNodeSetParams 778
#define RPC_cudaGraphAddChildGraphNode 779
#define RPC_cudaGraphChildGraphNodeGetGraph 780
#define RPC_cudaGraphAddEmptyNode 781
#define RPC_cudaGraphAddEventRecordNode 782
#define RPC_cudaGraphEventRecordNodeGetEvent 783
#define RPC_cudaGraphEventRecordNodeSetEvent 784
#define RPC_cudaGraphAddEventWaitNode 785
#define RPC_cudaGraphEventWaitNodeGetEvent 786
#define RPC_cudaGraphEventWaitNodeSetEvent 787
#define RPC_cudaGraphAddExternalSemaphoresSignalNode 788
#define RPC_cudaGraphExternalSemaphoresSignalNodeGetParams 789
#define RPC_cudaGraphExternalSemaphoresSignalNodeSetParams 790
#define RPC_cudaGraphAddExternalSemaphoresWaitNode 791
#define RPC_cudaGraphExternalSemaphoresWaitNodeGetParams 792
#define RPC_cudaGraphExternalSemaphoresWaitNodeSetParams 793
#define RPC_cudaGraphAddMemAllocNode 794
#define RPC_cudaGraphMemAllocNodeGetParams 795
#define RPC_cudaGraphAddMemFreeNode 796
#define RPC_cudaDeviceGraphMemTrim 797
#define RPC_cudaDeviceGetGraphMemAttribute 798
#define RPC_cudaGraphClone 799
#define RPC_cudaGraphNodeFindInClone 800
#define RPC_cudaGraphNodeGetType 801
#define RPC_cudaGraphGetNodes 802
#define RPC_cudaGraphGetRootNodes 803
#define RPC_cudaGraphGetEdges 804
#define RPC_cudaGraphNodeGetDependencies 805
#define RPC_cudaGraphNodeGetDependentNodes 806
#define RPC_cudaGraphAddDependencies 807
#define RPC_cudaGraphRemoveDependencies 808
#define RPC_cudaGraphDestroyNode 809
#define RPC_cudaGraphInstantiate 810
#define RPC_cudaGraphInstantiateWithFlags 811
#define RPC_cudaGraphInstantiateWithParams 812
#define RPC_cudaGraphExecGetFlags 813
#define RPC_cudaGraphExecKernelNodeSetParams 814
#define RPC_cudaGraphExecMemcpyNodeSetParams 815
#define RPC_cudaGraphExecMemcpyNodeSetParamsToSymbol 816
#define RPC_cudaGraphExecMemsetNodeSetParams 817
#define RPC_cudaGraphExecHostNodeSetParams 818
#define RPC_cudaGraphExecChildGraphNodeSetParams 819
#define RPC_cudaGraphExecEventRecordNodeSetEvent 820
#define RPC_cudaGraphExecEventWaitNodeSetEvent 821
#define RPC_cudaGraphExecExternalSemaphoresSignalNodeSetParams 822
#define RPC_cudaGraphExecExternalSemaphoresWaitNodeSetParams 823
#define RPC_cudaGraphNodeSetEnabled 824
#define RPC_cudaGraphNodeGetEnabled 825
#define RPC_cudaGraphExecUpdate 826
#define RPC_cudaGraphUpload 827
#define RPC_cudaGraphLaunch 828
#define RPC_cudaGraphExecDestroy 829
#define RPC_cudaGraphDestroy 830
#define RPC_cudaGraphDebugDotPrint 831
#define RPC_cudaUserObjectRetain 832
#define RPC_cudaUserObjectRelease 833
#define RPC_cudaGraphRetainUserObject 834
#define RPC_cudaGraphReleaseUserObject 835
#define RPC_cudaGetDriverEntryPoint 836
#define RPC_cudaGetExportTable 837
#define RPC_cudaGetFuncBySymbol 838
#define RPC_cublasCreate_v2 839
#define RPC_cublasDestroy_v2 840
#define RPC_cublasGetVersion_v2 841
#define RPC_cublasGetProperty 842
#define RPC_cublasGetCudartVersion 843
#define RPC_cublasSetWorkspace_v2 844
#define RPC_cublasSetStream_v2 845
#define RPC_cublasGetStream_v2 846
#define RPC_cublasGetPointerMode_v2 847
#define RPC_cublasSetPointerMode_v2 848
#define RPC_cublasGetAtomicsMode 849
#define RPC_cublasSetAtomicsMode 850
#define RPC_cublasGetMathMode 851
#define RPC_cublasSetMathMode 852
#define RPC_cublasGetSmCountTarget 853
#define RPC_cublasSetSmCountTarget 854
#define RPC_cublasGetStatusName 855
#define RPC_cublasGetStatusString 856
#define RPC_cublasLoggerConfigure 857
#define RPC_cublasSetLoggerCallback 858
#define RPC_cublasGetLoggerCallback 859
#define RPC_cublasXerbla 860
#define RPC_cublasSnrm2_v2 861
#define RPC_cublasSnrm2_v2_64 862
#define RPC_cublasDnrm2_v2 863
#define RPC_cublasDnrm2_v2_64 864
#define RPC_cublasScnrm2_v2 865
#define RPC_cublasScnrm2_v2_64 866
#define RPC_cublasDznrm2_v2 867
#define RPC_cublasDznrm2_v2_64 868
#define RPC_cublasSdot_v2 869
#define RPC_cublasSdot_v2_64 870
#define RPC_cublasDdot_v2 871
#define RPC_cublasDdot_v2_64 872
#define RPC_cublasCdotu_v2 873
#define RPC_cublasCdotu_v2_64 874
#define RPC_cublasCdotc_v2 875
#define RPC_cublasCdotc_v2_64 876
#define RPC_cublasZdotu_v2 877
#define RPC_cublasZdotu_v2_64 878
#define RPC_cublasZdotc_v2 879
#define RPC_cublasZdotc_v2_64 880
#define RPC_cublasSscal_v2 881
#define RPC_cublasSscal_v2_64 882
#define RPC_cublasDscal_v2 883
#define RPC_cublasDscal_v2_64 884
#define RPC_cublasCscal_v2 885
#define RPC_cublasCscal_v2_64 886
#define RPC_cublasCsscal_v2 887
#define RPC_cublasCsscal_v2_64 888
#define RPC_cublasZscal_v2 889
#define RPC_cublasZscal_v2_64 890
#define RPC_cublasZdscal_v2 891
#define RPC_cublasZdscal_v2_64 892
#define RPC_cublasSaxpy_v2 893
#define RPC_cublasSaxpy_v2_64 894
#define RPC_cublasDaxpy_v2 895
#define RPC_cublasDaxpy_v2_64 896
#define RPC_cublasCaxpy_v2 897
#define RPC_cublasCaxpy_v2_64 898
#define RPC_cublasZaxpy_v2 899
#define RPC_cublasZaxpy_v2_64 900
#define RPC_cublasScopy_v2 901
#define RPC_cublasScopy_v2_64 902
#define RPC_cublasDcopy_v2 903
#define RPC_cublasDcopy_v2_64 904
#define RPC_cublasCcopy_v2 905
#define RPC_cublasCcopy_v2_64 906
#define RPC_cublasZcopy_v2 907
#define RPC_cublasZcopy_v2_64 908
#define RPC_cublasSswap_v2 909
#define RPC_cublasSswap_v2_64 910
#define RPC_cublasDswap_v2 911
#define RPC_cublasDswap_v2_64 912
#define RPC_cublasCswap_v2 913
#define RPC_cublasCswap_v2_64 914
#define RPC_cublasZswap_v2 915
#define RPC_cublasZswap_v2_64 916
#define RPC_cublasIsamax_v2 917
#define RPC_cublasIsamax_v2_64 918
#define RPC_cublasIdamax_v2 919
#define RPC_cublasIdamax_v2_64 920
#define RPC_cublasIcamax_v2 921
#define RPC_cublasIcamax_v2_64 922
#define RPC_cublasIzamax_v2 923
#define RPC_cublasIzamax_v2_64 924
#define RPC_cublasIamaxEx 925
#define RPC_cublasIamaxEx_64 926
#define RPC_cublasIsamin_v2 927
#define RPC_cublasIsamin_v2_64 928
#define RPC_cublasIdamin_v2 929
#define RPC_cublasIdamin_v2_64 930
#define RPC_cublasIcamin_v2 931
#define RPC_cublasIcamin_v2_64 932
#define RPC_cublasIzamin_v2 933
#define RPC_cublasIzamin_v2_64 934
#define RPC_cublasIaminEx 935
#define RPC_cublasIaminEx_64 936
#define RPC_cublasSasum_v2 937
#define RPC_cublasSasum_v2_64 938
#define RPC_cublasDasum_v2 939
#define RPC_cublasDasum_v2_64 940
#define RPC_cublasScasum_v2 941
#define RPC_cublasScasum_v2_64 942
#define RPC_cublasDzasum_v2 943
#define RPC_cublasDzasum_v2_64 944
#define RPC_cublasSrot_v2 945
#define RPC_cublasSrot_v2_64 946
#define RPC_cublasDrot_v2 947
#define RPC_cublasDrot_v2_64 948
#define RPC_cublasCrot_v2 949
#define RPC_cublasCrot_v2_64 950
#define RPC_cublasCsrot_v2 951
#define RPC_cublasCsrot_v2_64 952
#define RPC_cublasZrot_v2 953
#define RPC_cublasZrot_v2_64 954
#define RPC_cublasZdrot_v2 955
#define RPC_cublasZdrot_v2_64 956
#define RPC_cublasSrotg_v2 957
#define RPC_cublasDrotg_v2 958
#define RPC_cublasCrotg_v2 959
#define RPC_cublasZrotg_v2 960
#define RPC_cublasSrotm_v2 961
#define RPC_cublasSrotm_v2_64 962
#define RPC_cublasDrotm_v2 963
#define RPC_cublasDrotm_v2_64 964
#define RPC_cublasSrotmg_v2 965
#define RPC_cublasDrotmg_v2 966
#define RPC_cublasSgemv_v2 967
#define RPC_cublasSgemv_v2_64 968
#define RPC_cublasDgemv_v2 969
#define RPC_cublasDgemv_v2_64 970
#define RPC_cublasCgemv_v2 971
#define RPC_cublasCgemv_v2_64 972
#define RPC_cublasZgemv_v2 973
#define RPC_cublasZgemv_v2_64 974
#define RPC_cublasSgbmv_v2 975
#define RPC_cublasSgbmv_v2_64 976
#define RPC_cublasDgbmv_v2 977
#define RPC_cublasDgbmv_v2_64 978
#define RPC_cublasCgbmv_v2 979
#define RPC_cublasCgbmv_v2_64 980
#define RPC_cublasZgbmv_v2 981
#define RPC_cublasZgbmv_v2_64 982
#define RPC_cublasStrmv_v2 983
#define RPC_cublasStrmv_v2_64 984
#define RPC_cublasDtrmv_v2 985
#define RPC_cublasDtrmv_v2_64 986
#define RPC_cublasCtrmv_v2 987
#define RPC_cublasCtrmv_v2_64 988
#define RPC_cublasZtrmv_v2 989
#define RPC_cublasZtrmv_v2_64 990
#define RPC_cublasStbmv_v2 991
#define RPC_cublasStbmv_v2_64 992
#define RPC_cublasDtbmv_v2 993
#define RPC_cublasDtbmv_v2_64 994
#define RPC_cublasCtbmv_v2 995
#define RPC_cublasCtbmv_v2_64 996
#define RPC_cublasZtbmv_v2 997
#define RPC_cublasZtbmv_v2_64 998
#define RPC_cublasStpmv_v2 999
#define RPC_cublasStpmv_v2_64 1000
#define RPC_cublasDtpmv_v2 1001
#define RPC_cublasDtpmv_v2_64 1002
#define RPC_cublasCtpmv_v2 1003
#define RPC_cublasCtpmv_v2_64 1004
#define RPC_cublasZtpmv_v2 1005
#define RPC_cublasZtpmv_v2_64 1006
#define RPC_cublasStrsv_v2 1007
#define RPC_cublasStrsv_v2_64 1008
#define RPC_cublasDtrsv_v2 1009
#define RPC_cublasDtrsv_v2_64 1010
#define RPC_cublasCtrsv_v2 1011
#define RPC_cublasCtrsv_v2_64 1012
#define RPC_cublasZtrsv_v2 1013
#define RPC_cublasZtrsv_v2_64 1014
#define RPC_cublasStpsv_v2 1015
#define RPC_cublasStpsv_v2_64 1016
#define RPC_cublasDtpsv_v2 1017
#define RPC_cublasDtpsv_v2_64 1018
#define RPC_cublasCtpsv_v2 1019
#define RPC_cublasCtpsv_v2_64 1020
#define RPC_cublasZtpsv_v2 1021
#define RPC_cublasZtpsv_v2_64 1022
#define RPC_cublasStbsv_v2 1023
#define RPC_cublasStbsv_v2_64 1024
#define RPC_cublasDtbsv_v2 1025
#define RPC_cublasDtbsv_v2_64 1026
#define RPC_cublasCtbsv_v2 1027
#define RPC_cublasCtbsv_v2_64 1028
#define RPC_cublasZtbsv_v2 1029
#define RPC_cublasZtbsv_v2_64 1030
#define RPC_cublasSsymv_v2 1031
#define RPC_cublasSsymv_v2_64 1032
#define RPC_cublasDsymv_v2 1033
#define RPC_cublasDsymv_v2_64 1034
#define RPC_cublasCsymv_v2 1035
#define RPC_cublasCsymv_v2_64 1036
#define RPC_cublasZsymv_v2 1037
#define RPC_cublasZsymv_v2_64 1038
#define RPC_cublasChemv_v2 1039
#define RPC_cublasChemv_v2_64 1040
#define RPC_cublasZhemv_v2 1041
#define RPC_cublasZhemv_v2_64 1042
#define RPC_cublasSsbmv_v2 1043
#define RPC_cublasSsbmv_v2_64 1044
#define RPC_cublasDsbmv_v2 1045
#define RPC_cublasDsbmv_v2_64 1046
#define RPC_cublasChbmv_v2 1047
#define RPC_cublasChbmv_v2_64 1048
#define RPC_cublasZhbmv_v2 1049
#define RPC_cublasZhbmv_v2_64 1050
#define RPC_cublasSspmv_v2 1051
#define RPC_cublasSspmv_v2_64 1052
#define RPC_cublasDspmv_v2 1053
#define RPC_cublasDspmv_v2_64 1054
#define RPC_cublasChpmv_v2 1055
#define RPC_cublasChpmv_v2_64 1056
#define RPC_cublasZhpmv_v2 1057
#define RPC_cublasZhpmv_v2_64 1058
#define RPC_cublasSger_v2 1059
#define RPC_cublasSger_v2_64 1060
#define RPC_cublasDger_v2 1061
#define RPC_cublasDger_v2_64 1062
#define RPC_cublasCgeru_v2 1063
#define RPC_cublasCgeru_v2_64 1064
#define RPC_cublasCgerc_v2 1065
#define RPC_cublasCgerc_v2_64 1066
#define RPC_cublasZgeru_v2 1067
#define RPC_cublasZgeru_v2_64 1068
#define RPC_cublasZgerc_v2 1069
#define RPC_cublasZgerc_v2_64 1070
#define RPC_cublasSsyr_v2 1071
#define RPC_cublasSsyr_v2_64 1072
#define RPC_cublasDsyr_v2 1073
#define RPC_cublasDsyr_v2_64 1074
#define RPC_cublasCsyr_v2 1075
#define RPC_cublasCsyr_v2_64 1076
#define RPC_cublasZsyr_v2 1077
#define RPC_cublasZsyr_v2_64 1078
#define RPC_cublasCher_v2 1079
#define RPC_cublasCher_v2_64 1080
#define RPC_cublasZher_v2 1081
#define RPC_cublasZher_v2_64 1082
#define RPC_cublasSspr_v2 1083
#define RPC_cublasSspr_v2_64 1084
#define RPC_cublasDspr_v2 1085
#define RPC_cublasDspr_v2_64 1086
#define RPC_cublasChpr_v2 1087
#define RPC_cublasChpr_v2_64 1088
#define RPC_cublasZhpr_v2 1089
#define RPC_cublasZhpr_v2_64 1090
#define RPC_cublasSsyr2_v2 1091
#define RPC_cublasSsyr2_v2_64 1092
#define RPC_cublasDsyr2_v2 1093
#define RPC_cublasDsyr2_v2_64 1094
#define RPC_cublasCsyr2_v2 1095
#define RPC_cublasCsyr2_v2_64 1096
#define RPC_cublasZsyr2_v2 1097
#define RPC_cublasZsyr2_v2_64 1098
#define RPC_cublasCher2_v2 1099
#define RPC_cublasCher2_v2_64 1100
#define RPC_cublasZher2_v2 1101
#define RPC_cublasZher2_v2_64 1102
#define RPC_cublasSspr2_v2 1103
#define RPC_cublasSspr2_v2_64 1104
#define RPC_cublasDspr2_v2 1105
#define RPC_cublasDspr2_v2_64 1106
#define RPC_cublasChpr2_v2 1107
#define RPC_cublasChpr2_v2_64 1108
#define RPC_cublasZhpr2_v2 1109
#define RPC_cublasZhpr2_v2_64 1110
#define RPC_cublasSgemvBatched 1111
#define RPC_cublasTSTgemvBatched 1112
#define RPC_cublasSgemvStridedBatched 1113
#define RPC_cublasSgemvStridedBatched_64 1114
#define RPC_cublasDgemvStridedBatched 1115
#define RPC_cublasDgemvStridedBatched_64 1116
#define RPC_cublasCgemvStridedBatched 1117
#define RPC_cublasCgemvStridedBatched_64 1118
#define RPC_cublasZgemvStridedBatched 1119
#define RPC_cublasZgemvStridedBatched_64 1120
#define RPC_cublasHSHgemvStridedBatched 1121
#define RPC_cublasHSHgemvStridedBatched_64 1122
#define RPC_cublasHSSgemvStridedBatched 1123
#define RPC_cublasHSSgemvStridedBatched_64 1124
#define RPC_cublasTSTgemvStridedBatched 1125
#define RPC_cublasTSTgemvStridedBatched_64 1126
#define RPC_cublasTSSgemvStridedBatched 1127
#define RPC_cublasTSSgemvStridedBatched_64 1128
#define RPC_cublasSgemm_v2 1129
#define RPC_cublasSgemm_v2_64 1130
#define RPC_cublasDgemm_v2 1131
#define RPC_cublasDgemm_v2_64 1132
#define RPC_cublasCgemm_v2 1133
#define RPC_cublasCgemm_v2_64 1134
#define RPC_cublasCgemm3m 1135
#define RPC_cublasCgemm3m_64 1136
#define RPC_cublasZgemm_v2 1137
#define RPC_cublasZgemm_v2_64 1138
#define RPC_cublasZgemm3m 1139
#define RPC_cublasZgemm3m_64 1140
#define RPC_cublasHgemm 1141
#define RPC_cublasHgemm_64 1142
#define RPC_cublasSsyrk_v2 1143
#define RPC_cublasSsyrk_v2_64 1144
#define RPC_cublasDsyrk_v2 1145
#define RPC_cublasDsyrk_v2_64 1146
#define RPC_cublasCsyrk_v2 1147
#define RPC_cublasCsyrk_v2_64 1148
#define RPC_cublasZsyrk_v2 1149
#define RPC_cublasZsyrk_v2_64 1150
#define RPC_cublasCherk_v2 1151
#define RPC_cublasCherk_v2_64 1152
#define RPC_cublasZherk_v2 1153
#define RPC_cublasZherk_v2_64 1154
#define RPC_cublasSsyr2k_v2 1155
#define RPC_cublasSsyr2k_v2_64 1156
#define RPC_cublasDsyr2k_v2 1157
#define RPC_cublasDsyr2k_v2_64 1158
#define RPC_cublasCsyr2k_v2 1159
#define RPC_cublasCsyr2k_v2_64 1160
#define RPC_cublasZsyr2k_v2 1161
#define RPC_cublasZsyr2k_v2_64 1162
#define RPC_cublasCher2k_v2 1163
#define RPC_cublasCher2k_v2_64 1164
#define RPC_cublasZher2k_v2 1165
#define RPC_cublasZher2k_v2_64 1166
#define RPC_cublasSsyrkx 1167
#define RPC_cublasSsyrkx_64 1168
#define RPC_cublasDsyrkx 1169
#define RPC_cublasDsyrkx_64 1170
#define RPC_cublasCsyrkx 1171
#define RPC_cublasCsyrkx_64 1172
#define RPC_cublasZsyrkx 1173
#define RPC_cublasZsyrkx_64 1174
#define RPC_cublasCherkx 1175
#define RPC_cublasCherkx_64 1176
#define RPC_cublasZherkx 1177
#define RPC_cublasZherkx_64 1178
#define RPC_cublasSsymm_v2 1179
#define RPC_cublasSsymm_v2_64 1180
#define RPC_cublasDsymm_v2 1181
#define RPC_cublasDsymm_v2_64 1182
#define RPC_cublasCsymm_v2 1183
#define RPC_cublasCsymm_v2_64 1184
#define RPC_cublasZsymm_v2 1185
#define RPC_cublasZsymm_v2_64 1186
#define RPC_cublasChemm_v2 1187
#define RPC_cublasChemm_v2_64 1188
#define RPC_cublasZhemm_v2 1189
#define RPC_cublasZhemm_v2_64 1190
#define RPC_cublasStrsm_v2 1191
#define RPC_cublasStrsm_v2_64 1192
#define RPC_cublasDtrsm_v2 1193
#define RPC_cublasDtrsm_v2_64 1194
#define RPC_cublasCtrsm_v2 1195
#define RPC_cublasCtrsm_v2_64 1196
#define RPC_cublasZtrsm_v2 1197
#define RPC_cublasZtrsm_v2_64 1198
#define RPC_cublasStrmm_v2 1199
#define RPC_cublasStrmm_v2_64 1200
#define RPC_cublasDtrmm_v2 1201
#define RPC_cublasDtrmm_v2_64 1202
#define RPC_cublasCtrmm_v2 1203
#define RPC_cublasCtrmm_v2_64 1204
#define RPC_cublasZtrmm_v2 1205
#define RPC_cublasZtrmm_v2_64 1206
#define RPC_cublasHgemmBatched 1207
#define RPC_cublasHgemmBatched_64 1208
#define RPC_cublasSgemmBatched 1209
#define RPC_cublasSgemmBatched_64 1210
#define RPC_cublasDgemmBatched 1211
#define RPC_cublasDgemmBatched_64 1212
#define RPC_cublasCgemmBatched 1213
#define RPC_cublasCgemmBatched_64 1214
#define RPC_cublasCgemm3mBatched 1215
#define RPC_cublasCgemm3mBatched_64 1216
#define RPC_cublasZgemmBatched 1217
#define RPC_cublasZgemmBatched_64 1218
#define RPC_cublasHgemmStridedBatched 1219
#define RPC_cublasHgemmStridedBatched_64 1220
#define RPC_cublasSgemmStridedBatched 1221
#define RPC_cublasSgemmStridedBatched_64 1222
#define RPC_cublasDgemmStridedBatched 1223
#define RPC_cublasDgemmStridedBatched_64 1224
#define RPC_cublasCgemmStridedBatched 1225
#define RPC_cublasCgemmStridedBatched_64 1226
#define RPC_cublasCgemm3mStridedBatched 1227
#define RPC_cublasCgemm3mStridedBatched_64 1228
#define RPC_cublasZgemmStridedBatched 1229
#define RPC_cublasZgemmStridedBatched_64 1230
#define RPC_cublasGemmBatchedEx 1231
#define RPC_cublasGemmBatchedEx_64 1232
#define RPC_cublasSgeam 1233
#define RPC_cublasSgeam_64 1234
#define RPC_cublasDgeam 1235
#define RPC_cublasDgeam_64 1236
#define RPC_cublasCgeam 1237
#define RPC_cublasCgeam_64 1238
#define RPC_cublasZgeam 1239
#define RPC_cublasZgeam_64 1240
#define RPC_cublasStrsmBatched 1241
#define RPC_cublasStrsmBatched_64 1242
#define RPC_cublasDtrsmBatched 1243
#define RPC_cublasDtrsmBatched_64 1244
#define RPC_cublasCtrsmBatched 1245
#define RPC_cublasCtrsmBatched_64 1246
#define RPC_cublasZtrsmBatched 1247
#define RPC_cublasZtrsmBatched_64 1248
#define RPC_cublasSdgmm 1249
#define RPC_cublasSdgmm_64 1250
#define RPC_cublasDdgmm 1251
#define RPC_cublasDdgmm_64 1252
#define RPC_cublasCdgmm 1253
#define RPC_cublasCdgmm_64 1254
#define RPC_cublasZdgmm 1255
#define RPC_cublasZdgmm_64 1256
#define RPC_cublasSmatinvBatched 1257
#define RPC_cublasDmatinvBatched 1258
#define RPC_cublasCmatinvBatched 1259
#define RPC_cublasZmatinvBatched 1260
#define RPC_cublasSgeqrfBatched 1261
#define RPC_cublasDgeqrfBatched 1262
#define RPC_cublasCgeqrfBatched 1263
#define RPC_cublasZgeqrfBatched 1264
#define RPC_cublasSgelsBatched 1265
#define RPC_cublasDgelsBatched 1266
#define RPC_cublasCgelsBatched 1267
#define RPC_cublasZgelsBatched 1268
#define RPC_cublasStpttr 1269
#define RPC_cublasDtpttr 1270
#define RPC_cublasCtpttr 1271
#define RPC_cublasZtpttr 1272
#define RPC_cublasStrttp 1273
#define RPC_cublasDtrttp 1274
#define RPC_cublasCtrttp 1275
#define RPC_cublasZtrttp 1276
#define RPC_cublasSgetrfBatched 1277
#define RPC_cublasDgetrfBatched 1278
#define RPC_cublasCgetrfBatched 1279
#define RPC_cublasZgetrfBatched 1280
#define RPC_cublasSgetriBatched 1281
#define RPC_cublasDgetriBatched 1282
#define RPC_cublasCgetriBatched 1283
#define RPC_cublasZgetriBatched 1284
#define RPC_cublasSgetrsBatched 1285
#define RPC_cublasDgetrsBatched 1286
#define RPC_cublasCgetrsBatched 1287
#define RPC_cublasZgetrsBatched 1288
#define RPC_cublasUint8gemmBias 1289
#define RPC_cublasMigrateComputeType 1290
#define RPC_cudnnGetMaxDeviceVersion 1291
#define RPC_cudnnGetCudartVersion 1292
#define RPC_cudnnGetErrorString 1293
#define RPC_cudnnGetLastErrorString 1294
#define RPC_cudnnQueryRuntimeError 1295
#define RPC_cudnnGetProperty 1296
#define RPC_cudnnCreate 1297
#define RPC_cudnnDestroy 1298
#define RPC_cudnnSetStream 1299
#define RPC_cudnnGetStream 1300
#define RPC_cudnnGetCallback 1301
#define RPC_cudnnGraphVersionCheck 1302
#define RPC_cudnnBackendCreateDescriptor 1303
#define RPC_cudnnBackendDestroyDescriptor 1304
#define RPC_cudnnBackendInitialize 1305
#define RPC_cudnnBackendFinalize 1306
#define RPC_cudnnBackendSetAttribute 1307
#define RPC_cudnnBackendExecute 1308
#define RPC_cudnnCreateTensorDescriptor 1309
#define RPC_cudnnSetTensor4dDescriptor 1310
#define RPC_cudnnSetTensor4dDescriptorEx 1311
#define RPC_cudnnGetTensor4dDescriptor 1312
#define RPC_cudnnGetTensorSizeInBytes 1313
#define RPC_cudnnDestroyTensorDescriptor 1314
#define RPC_cudnnInitTransformDest 1315
#define RPC_cudnnCreateTensorTransformDescriptor 1316
#define RPC_cudnnDestroyTensorTransformDescriptor 1317
#define RPC_cudnnCreateOpTensorDescriptor 1318
#define RPC_cudnnSetOpTensorDescriptor 1319
#define RPC_cudnnGetOpTensorDescriptor 1320
#define RPC_cudnnDestroyOpTensorDescriptor 1321
#define RPC_cudnnCreateReduceTensorDescriptor 1322
#define RPC_cudnnSetReduceTensorDescriptor 1323
#define RPC_cudnnGetReduceTensorDescriptor 1324
#define RPC_cudnnDestroyReduceTensorDescriptor 1325
#define RPC_cudnnGetReductionIndicesSize 1326
#define RPC_cudnnGetReductionWorkspaceSize 1327
#define RPC_cudnnCreateFilterDescriptor 1328
#define RPC_cudnnSetFilter4dDescriptor 1329
#define RPC_cudnnGetFilter4dDescriptor 1330
#define RPC_cudnnGetFilterSizeInBytes 1331
#define RPC_cudnnDestroyFilterDescriptor 1332
#define RPC_cudnnCreatePoolingDescriptor 1333
#define RPC_cudnnSetPooling2dDescriptor 1334
#define RPC_cudnnGetPooling2dDescriptor 1335
#define RPC_cudnnGetPooling2dForwardOutputDim 1336
#define RPC_cudnnDestroyPoolingDescriptor 1337
#define RPC_cudnnCreateActivationDescriptor 1338
#define RPC_cudnnSetActivationDescriptor 1339
#define RPC_cudnnGetActivationDescriptor 1340
#define RPC_cudnnSetActivationDescriptorSwishBeta 1341
#define RPC_cudnnGetActivationDescriptorSwishBeta 1342
#define RPC_cudnnDestroyActivationDescriptor 1343
#define RPC_cudnnActivationForward 1344
#define RPC_cudnnCreateLRNDescriptor 1345
#define RPC_cudnnSetLRNDescriptor 1346
#define RPC_cudnnGetLRNDescriptor 1347
#define RPC_cudnnDestroyLRNDescriptor 1348
#define RPC_cudnnDeriveBNTensorDescriptor 1349
#define RPC_cudnnDeriveNormTensorDescriptor 1350
#define RPC_cudnnCreateSpatialTransformerDescriptor 1351
#define RPC_cudnnDestroySpatialTransformerDescriptor 1352
#define RPC_cudnnCreateDropoutDescriptor 1353
#define RPC_cudnnDestroyDropoutDescriptor 1354
#define RPC_cudnnDropoutGetStatesSize 1355
#define RPC_cudnnDropoutGetReserveSpaceSize 1356
#define RPC_cudnnGetDropoutDescriptor 1357
#define RPC_cudnnOpsVersionCheck 1358
#define RPC_cudnnGetBatchNormalizationForwardTrainingExWorkspaceSize 1359
#define RPC_cudnnGetBatchNormalizationBackwardExWorkspaceSize 1360
#define RPC_cudnnGetBatchNormalizationTrainingExReserveSpaceSize 1361
#define RPC_cudnnGetNormalizationForwardTrainingWorkspaceSize 1362
#define RPC_cudnnGetNormalizationBackwardWorkspaceSize 1363
#define RPC_cudnnGetNormalizationTrainingReserveSpaceSize 1364
